//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldata_documents
    {
        public int id { get; set; }
        public string headertext { get; set; }
        public string numorder { get; set; }
        public int doctype { get; set; }
        public System.DateTime docdate { get; set; }
        public string path { get; set; }
    }
}
